import Head from 'next/head'
import { Inter } from 'next/font/google'
import client from '../apolliClient'
import { NEW_QUERY } from '../graphql/myQuery'


const inter = Inter({ subsets: ['latin'] })

const Home = ({data}) =>{

  const posts =data.posts.edges
  console.log(posts)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <h1>Posts</h1>
      <ul>
      {posts.map(({ node }) => (
        <li key={node.id}>
          <h2>{node.title}</h2>
          <p dangerouslySetInnerHTML={{ __html: node.content }} />
        </li>
      ))}
    </ul>
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: NEW_QUERY,
  });

  return {
    props: {
      data,
    },
  };
}

export default Home